import os
import json
import google.generativeai as genai
from dotenv import load_dotenv
from src.agents.base import BaseAgent
from src.utils.schemas import Action, Plan
from typing import List, Any
from pydantic import ValidationError

load_dotenv()

class PlannerAgent(BaseAgent):
    """
    Agent responsible for decomposing user requests into a structured plan of actions.
    Uses the Gemini API to perform natural language understanding and decomposition.
    """
    def __init__(self):
        super().__init__("PlannerAgent", "Decompose complex requests into structured actions using Gemini")
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            self.logger.error("missing_api_key", message="GEMINI_API_KEY not found in environment")
            raise ValueError("GEMINI_API_KEY must be set in .env")
        
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel('gemini-flash-latest')

    async def execute(self, action: Action) -> Any:
        # Planner itself doesn't execute tool actions
        pass

    async def create_plan(self, prompt: str) -> Plan:
        """
        Calls Gemini to decompose the user prompt into a list of structured actions.
        """
        self.logger.info("creating_plan_with_gemini", prompt=prompt)
        
        system_prompt = """
        You are the 'Neural Orchestrator' for AgentFlow, an elite multi-agent swarm.
        Your goal is to decompose a user request into a sequence of structured actions while maintaining Deep Memory synchronization.
        
        Available Agents and Tools:
        1. Agent: 'task'
           Tools: 'create_task(title, description)', 'list_tasks()', 'complete_task(task_id)'
        2. Agent: 'calendar'
           Tools: 'create_event(title, start_time, location)', 'list_events()', 'delete_event(event_id)'
        3. Agent: 'notes'
           Tools: 'save_note(title, content)', 'search_notes(query)', 'delete_note(note_id)'
        4. Agent: 'research'
           Tools: 'research_topic(query)' (Gather external facts or inspirations)
        
        DEEP MEMORY PROTOCOL:
        If the request involves names, preferences, locations, or recurring topics, you MUST initiate a 'notes.search_notes' call as the first step to retrieve personal context.
        
        ELITE PERSONALITY:
        Your 'rationale' should be professional, technical, and confident. Use terms like 'Synchronizing', 'Orchestrating', and 'Deploying'.
        
        Output format:
        You MUST return a JSON object with two fields:
        - "actions": A list of objects with "agent", "tool", and "params".
        - "rationale": A high-end explanation of the plan.
        
        CRITICAL: All 'start_time' parameters MUST be in valid ISO 8601 format (YYYY-MM-DDTHH:MM:SS), e.g., '2026-04-07T10:00:00'. If the user says 'tomorrow', calculate the date relative to today (2026-04-06).
        
        Example Output:
        {
          "actions": [
            {"agent": "notes", "tool": "search_notes", "params": {"query": "preferences"}},
            {"agent": "calendar", "tool": "create_event", "params": {"title": "Strategic Meeting", "start_time": "2026-04-07T10:00:00"}}
          ],
          "rationale": "Orchestrating a strategic event while synchronizing with deep memory context."
        }
        
        Return ONLY valid JSON.
        """
        
        try:
            response = await self.model.generate_content_async(
                f"{system_prompt}\n\nUser Request: {prompt}",
                generation_config={"response_mime_type": "application/json"}
            )
            
            content = response.text.strip()
            # Handle potential markdown code blocks in Gemini output
            if content.startswith("```json"):
                content = content[7:-3].strip()
            elif content.startswith("```"):
                content = content[3:-3].strip()
                
            data = json.loads(content)
            
            # Map LLM output to Plan model
            actions = [Action(**a) for a in data.get("actions", [])]
            return Plan(actions=actions, rationale=data.get("rationale", "Generated by AI"))
            
        except json.JSONDecodeError as e:
            self.logger.error("planner_json_parsing_error", error=str(e), content=content)
            return Plan(actions=[], rationale=f"Error parsing AI response: {str(e)}")
        except ValidationError as e:
            self.logger.error("planner_schema_validation_error", error=str(e))
            return Plan(actions=[], rationale=f"AI output did not match schema: {str(e)}")
        except Exception as e:
            self.logger.error("planner_unexpected_error", error=str(e))
            return Plan(actions=[], rationale=f"Unexpected error in planner: {str(e)}")
